# Don't change this `name` below, the script might broke at some point
name: "init banner"
on:
   workflow_dispatch:
   schedule:
     # You can change this CRON syntax to customize execute interval
     - cron: "0 */2 * * *"

jobs:
 checks:
    runs-on: ubuntu-latest
    steps:
      - name: "ownership check"
        if: ${{ github.triggering_actor != github.repository_owner }}
        run: |
          printf '%s\n' "Runner prevented to run because the script is executed by an untrusted user. (Only owner can execute, for security)" >&2
          exit 1

      - name: "get bot_runner workflow id"
        id: get_run_id
        run: |
          response="$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/bot_runner.yml/runs")"
          run_id="$(printf '%s' "${response}" | jq -r '.workflow_runs[0].id')"

      - name: "check status"
        id: check_status
        run: |
          response="$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.get_run_id.outputs.run_id }}")"
          status="$(printf '%s' "${response}" | jq -r '.status')"

      - name: "check if running"
        if: ${{ steps.check_status.outputs.status == 'in_progress' }}
        run: |
          printf '%s\n' "The bot_runner is still running, The script prevented this workflow to run to avoid conflicts... Cancelling!!" >&2
          exit 1

 inits:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "execute"
        run: bash img_process.sh "in_progress"

      - name: "commit banner"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "stat: Processing..."
          repository: .
          file_pattern: status/*.jpg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
