# Don't change this `name` below, the script might broke at some point
name: "init banner"
on:
   workflow_dispatch:

permissions:
  contents: write

jobs:
 checks:
    runs-on: ubuntu-24.04
    steps:
      - name: "ownership check"
        env:
          trig_actor: ${{ github.triggering_actor }}
          repo_ownr: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOK }}
        run: |
          case "${trig_actor}" in
            "${repo_ownr}"|github-actions*) : ;;
            *) printf '%s\n'"Runner prevented to run because the script is executed by an untrusted user \"${trig_actor}\". (Only owner can execute, for security)" >&2
               gh run cancel "${{ github.run_id }}" --repo "${{ github.repository }}" ;;
          esac

      - name: "chk wf status"
        id: check_status
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOK }}
        run: |
          response="$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/bot_runner.yml/runs")"
          status="$(echo "${response}" | jq -r '.workflow_runs[].status')"
          if grep -qE 'in_progress' <<< "${status}"; then
            echo -e '> [!CAUTION]'"\n> The bot_runner is still running, The script prevented this workflow to run to avoid conflicts... Cancelling"'!!' >> "${GITHUB_STEP_SUMMARY}"
            # Cancel Job
            gh run cancel "${{ github.run_id }}" --repo "${{ github.repository }}"
          fi
          : "Ignore"

 inits:
    runs-on: ubuntu-24.04
    if: success() && true
    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "check status"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOK }}
        run: |
          if [[ "$(<./fb/frameiterator)" -gt "$(sed -nE 's/.*total_frame="([^"]*)".*/\1/p' config.conf)" ]]; then
             echo -e '> [!NOTE]'"\n> The Bot was Finished Running" >> "${GITHUB_STEP_SUMMARY}"
             gh workflow disable trigger.yml --repo ${{ github.repository }}
             gh run cancel "${{ github.run_id }}" --repo "${{ github.repository }}"
          fi

      - name: "initialize package"
        run: |
          sudo apt install imagemagick -y

      - name: "execute"
        run: bash img_process.sh "in_progress"

      - name: "commit banner"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "stat: Processing..."
          repository: .
          file_pattern: status/*.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
